import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import { elGR } from '@clerk/localizations'
import { Toaster } from "@/components/ui/sonner"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider localization={elGR} appearance={{
      layout: {
        unsafe_disableDevelopmentModeWarnings: true,
      },
    }}>
    <html lang="en">
      
      <body >
        {children}
        <Toaster />
      </body>
    </html>
    </ClerkProvider>
  );
}
